<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Context\" />
    <Folder Include="Data\UnitOfWork\" />
    <Folder Include="ExternalServices\" />
    <Folder Include="Security\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaContable.Application\SistemaContable.Application.csproj" />
    <ProjectReference Include="..\SistemaContable.Domain\SistemaContable.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
